### ISSUE TITLE
懒人包无法运行，报错

### ISSUE THREAD

**Issue by Couslever** [Spr-Aachen/Easy-Voice-Toolkit#1]
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Windows\System32\nvml.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pynvml\nvml.py", line 1791, in _LoadNvmlLibrary
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Windows\\System32/nvml.dll'. Most likely this dynlib/dll was not found when the application was frozen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pynvml\nvml.py", line 1795, in _LoadNvmlLibrary
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Program Files\\NVIDIA Corporation/NVSMI/nvml.dll'. Most likely this dynlib/dll was not found when the application was frozen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projekt\Git\Python Projects\Easy-Voice-Toolkit\Run.py", line 6643, in <module>
  File "D:\Projekt\Git\Python Projects\Easy-Voice-Toolkit\Run.py", line 869, in __init__
  File "QEasyWidgets\QTasks.py", line 60, in __init__
  File "pynvml\nvml.py", line 1770, in nvmlInit
  File "pynvml\nvml.py", line 1753, in nvmlInitWithFlags
  File "pynvml\nvml.py", line 1800, in _LoadNvmlLibrary
  File "pynvml\nvml.py", line 833, in _nvmlCheckReturn
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

电脑为联想Thinkbook 14+ 2024
Intel Ultra 7 155H
32G LPDDR5X
无独显

根据以上报错信息，想知道是否需要独立的N卡？是否存在路径问题？

**Comment by Spr-Aachen** [comment]
您好，是需要独立显卡的且目前仅支持N卡
