### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Amazon90** [Spr-Aachen/Easy-Voice-Toolkit#2]
![20240606165316](https://github.com/Spr-Aachen/Easy-Voice-Toolkit/assets/72290820/f83808d0-0574-4eae-801f-bcff05f17a57)

```
Failed to execute script 'Run' due to unhandled exception?
'cp950' codec can't encode character "u58fo' in position 18
illegal multibyte seguence
```
```

Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "collections\__init__.py", line 941, in __getitem__
  File "collections\__init__.py", line 933, in __missing__
KeyError: 'denoise_target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "QEasyWidgets\Utils.py", line 813, in GetValue
  File "configparser.py", line 792, in get
configparser.NoOptionError: No option 'denoise_target' in section: 'Denoiser Params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projekt\Git\Python Projects\Backup\Easy-Voice-Toolkit\Run.py", line 7129, in <module>
  File "D:\Projekt\Git\Python Projects\Backup\Easy-Voice-Toolkit\Run.py", line 1689, in Main
  File "EVT_GUI\Functions.py", line 538, in SetParam
  File "QEasyWidgets\Utils.py", line 816, in GetValue
  File "QEasyWidgets\Utils.py", line 803, in EditConfig
  File "configparser.py", line 922, in write
  File "configparser.py", line 935, in _write_section
UnicodeEncodeError: 'cp950' codec can't encode character '\u58f0' in position 18: illegal multibyte sequence

```

**Comment by Spr-Aachen** [comment]
Hello there, is this the first time you run this software? And what's your system language?

**Comment by Spr-Aachen** [comment]
Figured out it's an encoding error, should be fixed in the next update.

**Comment by Amazon90** [comment]
> Figured out it's an encoding error, should be fixed in the next update.

Windows 11 Professional 23H2 22631.3593
NVIDIA GeForce RTX4070 Ti 32.0.15.558

**Comment by Amazon90** [comment]
> New version released, see if the bug has been fixed :)

Thanks, I'll try tomorrow.

**Comment by Spr-Aachen** [comment]
Newer version released, should be totally fixed at this time.
