### ISSUE TITLE
如何解决缺少Sources文件夹这个问题？

### ISSUE THREAD

**Issue by hezta** [Spr-Aachen/Easy-Voice-Toolkit#4]
(E:\hezt\easyvoice) E:\tool\Easy-Voice-Toolkit-1.1.5>python Run.py
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Process.png
QThread: Destroyed while thread is still running
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Layout.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Layout.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Layout.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Layout.png
Could not create pixmap from E:\tool\Easy-Voice-Toolkit-1.1.5\Sources\Guidance_Layout.png
Traceback (most recent call last):
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\Run.py", line 6655, in <module>
    MW.Main()
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\Run.py", line 1651, in Main
    Function_ConfigureCheckBox(
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\EVT_GUI\Functions.py", line 156, in Function_ConfigureCheckBox
    RunEvents(CheckedEvents) if TakeEffect and CheckBox.isChecked() else None
  File "E:\hezt\easyvoice\lib\site-packages\QEasyWidgets\Utils.py", line 417, in RunEvents
    Event() if Event is not None else None
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\Run.py", line 1655, in <lambda>
    lambda: Function_SetChildWidgetsVisibility(
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\EVT_GUI\Functions.py", line 115, in Function_SetChildWidgetsVisibility
    Function_AnimateFrame(
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\EVT_GUI\Functions.py", line 395, in Function_AnimateFrame
    ExtendFrame()
  File "E:\tool\Easy-Voice-Toolkit-1.1.5\EVT_GUI\Functions.py", line 388, in ExtendFrame
    Function_SetWidgetSizeAnimation(Frame, None, MaxHeight, Duration, SupportSplitter).start() if MaxHeight not in (None, Frame.height()) else None
TypeError: Function_SetWidgetSizeAnimation() takes from 1 to 4 positional arguments but 5 were given
QThread: Destroyed while thread is still running
好像缺少Easy-Voice-Toolkit-1.1.5\Sources\文件夹？

**Comment by Spr-Aachen** [comment]
是的，因为这些图像文件是动态加载的，而png文件又刚好被gitignore了所以会有这个问题。
之前因为图像文件过大所以没打算上传，如果觉得有必要的话我后面加一下条件判断屏蔽掉这些警告或者把图像编译到静态文件里。
